### ISSUE TITLE
Cannot open locked chest

### ISSUE THREAD

**Issue by Nachop2** [DevEkode/FabricLockette#16] opened 2021-07-02 16:40 UTC
**Describe the bug**
I lock a chest, after locking cannot open it

**To Reproduce**
1. Lock a chest
2. Try to open
3. See error

**Expected behavior**
Locked chest, that I can open

**Screenshots**
https://streamable.com/p5jtss

**Environnement versions:**
 - Minecraft version : 1.16.5
 - FabricLockette version : 0.2.1 (Curseforge version)

**Comment by DevEkode** [comment] 2021-08-18 16:33
Sorry to be that late on this issue.
What is the current status of your MC server (online or offline) ?

**Comment by hlarrainq** [comment] 2021-08-18 16:44
> Sorry to be that late on this issue.
> What is the current status of your MC server (online or offline) ?

My server is online

**Comment by hlarrainq** [comment] 2021-08-18 22:25
Any idea of why is this bug happening? This mod worked perfectly when you published the last version?
I was trying to find any solution with permissions but no luck :(

**Comment by DevEkode** [comment] 2021-08-18 22:33
Not at the moment, I need to do some debugging.
I do not have a lot of free time at the moment, so I'll do my best.

One thing that could help me, is to send me an MC save map with the chest and sign that you cannot open.
(I need to check those NBT tags)

**Comment by hlarrainq** [comment] 2021-08-21 03:40
Sorry for the late. I tested more in a private server, and this only works when online-mode is set true in server.properties. Sorry if that was the question, i understand other thing.
Is there any way to get this working in a offline mode server?
[Here](https://drive.google.com/file/d/1kdztSvc21PJquVvQbnyL82jsIlTKSty3/view?usp=sharing) you can download the map where i cant open the chest anyway if you need it.
Thanks!

**Comment by DevEkode** [comment] 2021-08-23 11:39
Okay thx for the map, I think it's an issue with the player UUID the mod is using.
I'll do some testing and update you when I find something !

**Comment by DevEkode** [comment] 2021-08-23 12:45
So found the issue :
- When you create a private sign, the mod uses Mojang API to query your UUID (if your account is premium)
- In `online-mode=false` the mod will not use the real Mojang UUID but a generated one.
- So `sign player UUID != generated player UUID` and it will refuse to open the container.

Exemple :
- Your create the sign, `Username = MrLarrain, UUID = 8796213b-ad2b-46fb-97db-ec0ee2d23f8b`
- `online-mode=true`, sign : `UUID = 8796213b-ad2b-46fb-97db-ec0ee2d23f8b`, player :  `UUID = 8796213b-ad2b-46fb-97db-ec0ee2d23f8b` => UUID match, open the chest.
- `online-mode=false`, sign : `UUID = 8796213b-ad2b-46fb-97db-ec0ee2d23f8b`, player :  `UUID = face422a-52e7-4662-b2b3-9edad3532241` => UUID does not match, lock the chest.

Solutions :
-  Use SimpleAuth (1.16) : https://www.curseforge.com/minecraft/mc-mods/simpleauth or EasyAuth (1.17) : https://www.curseforge.com/minecraft/mc-mods/easyauth.
- Do not switch from `online-mode=true` to `online-mode=false` after creating private signs, only use one mode.

**Comment by DevEkode** [comment] 2021-08-23 12:50
One thing I could do, is to save the player name as well as the UUID into the private sign.
So when using `online-mode=true` the mod will check the username and not the UUID.
(but you should add a mod like SimpleAuth to secure your server)

**Comment by hlarrainq** [comment] 2021-08-23 15:38
> One thing I could do, is to save the player name as well as the UUID into the private sign.
> So when using `online-mode=true` the mod will check the username and not the UUID.
> (but you should add a mod like SimpleAuth to secure your server)

That would be amazing. I am using a mod called SimplerAuth to secure my server, anyway FabricLockette never let the people open their own chests, and i never change online-mode.
Save the player name as well as the UUID seems a good solution.
Thx for the explanations :)

**Comment by DevEkode** [comment] 2021-08-24 08:54
I've done some implementation in the develop branch.
Could you test if FabricLockette works correctly now ?
Take the jar snapshot right here : https://github.com/DevEkode/FabricLockette/actions/runs/1161886771

**Comment by hlarrainq** [comment] 2021-08-24 16:23
> I've done some implementation in the develop branch.
> Could you test if FabricLockette works correctly now ?
> Take the jar snapshot right here : https://github.com/DevEkode/FabricLockette/actions/runs/1161886771

Thanks for the implementations. I tested it on a server only with this mod and it seems to work nice.
But i tested it on my public server, and when a player puts a sign with [Private] i get this error on console:

[16:19:47] [Server thread/FATAL]: Error executing task on Server
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:Private
        at net.minecraft.class_2960.<init>(class_2960.java:41) ~[intermediary-server.jar:?]
        at net.minecraft.class_2960.<init>(class_2960.java:46) ~[intermediary-server.jar:?]
        at net.minecraft.class_2625.method_5431(class_2625.java:1112) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31282(class_3244.java:1501) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31285(class_3244.java:1476) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31284(class_3244.java:314) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31280(class_3244.java:324) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]

It seems that when using more mods, FabricLockette stops working, but idk which is the incompatibility :(

**Comment by hlarrainq** [comment] 2021-08-24 16:42
Despite having this error on the console, the sign protects correctly the chests and the doors from other players. The text in the first line of the letter doesn't get bold.
The text of the sign with [Private] only seems visible to the person who protected.

**Comment by DevEkode** [comment] 2021-08-25 06:54
Indeed, seems to be an incompatibility with something else.
Could you give me more info about your private server :
- Fabric version
- Mods you are using (with versions if possible)

I'll try to reproduce the issue.

**Comment by hlarrainq** [comment] 2021-08-25 08:13
Ok, thx for the confirmation. After a lot of painful try and error, i found the incompatibility. It is with the mod [Gunpowder 0.5.7](https://www.curseforge.com/minecraft/mc-mods/gunpowder-mc) (the latest version for 1.16).

I ran a server with this mods, and the error can be reproduced:
- fabric-api-0.39.1+1.16
- fabric-language-kotlin-1.6.1+kotlin.1.5.10
- FabricLockette-mc1.16.x-0.1.0-dev.1+develop.7cbd32f
- gunpowder-base-0.5.7+1.16.5

I know that probably this error isnt your mod's fault. So maybe i will need to change of essentials mod for my server to use FabricLockette. I am running fabric 0.11.6.

**Comment by DevEkode** [comment] 2021-08-25 13:05
Thx for this "lot of painful try and error" work haha
I need to do some digging on this one, I've opened another issue #19 because the current one is much different.
You can follow it for updates.

I'll close this issue when the next version goes out.

**Comment by DevEkode** [comment] 2021-12-18 11:48
Closing the issue because the new release is out with the fix

**Closed by DevEkode** 2021-12-18 11:48 UTC
Labels: bug
